name = "MPIStaticCondensation"
uuid = "b5a239fd-4de5-41de-90c0-c60b4b9ba762"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
LinearAlgebra = "1.11.0"
MPI = "0.20.22"
MPIPreferences = "0.1.11"
SparseArrays = "1.11.0"
StableRNGs = "1"
TimerOutputs = "0.5.27"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StableRNGs", "Test"]
